name = "roulette-api-test"
main = "src/index.ts"
compatibility_date = "2025-10-18"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "ASSETS_KV"
id = "ff676cffb12944739d1c4cb46a86fbf8"

[[kv_namespaces]]
binding = "DEDUPE_KV"
id = "ff676cffb12944739d1c4cb46a86fbf8"

[[durable_objects.bindings]]
name = "QUEUE_DO"
class_name = "PrefetchQueue"

[[migrations]]
tag = "v1"
new_classes = ["PrefetchQueue"]

[vars]
MODEL_NAME = "gemini-1.5-flash"
